import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "swiper/css";
import NavBar from "./components/NavBar/NavBar";
import NextTopLoader from "nextjs-toploader";
import { Footer } from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  // title: "Movix",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} main-bg text-main`}>
        <NavBar />
        <NextTopLoader color="#da2f68" showSpinner={false} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
